// Parameter Definitions
#define NUMBER_OF_PARTICLES 10000
#define MIN_VELOCITY 10.0
#define MAX_VELOCITY -10.0
#define PARTICLE_MASS 1.0
#define PARTICLE_RADIUS 0.5
#define COLLISION_SPRING_CONSTANT (PARTICLE_MASS * (max(abs(MIN_VELOCITY), abs(MAX_VELOCITY))) * (max(abs(MIN_VELOCITY), abs(MAX_VELOCITY))) / ((PARTICLE_RADIUS) * (PARTICLE_RADIUS)))
#define SHEARING_CONSTANT 0.1
#define ATTRACTION_CONSTANT 0.01
#define GRAVITY_CONSTANT -10.0
#define GLOBAL_DAMPING_CONSTANT 0.1
#define BOUNDARY_DAMPING_CONSTANT 0.7
#define COLLISION_DAMPING_CONSTANT 0.1

// Dimension Definitions
#define BOUNDARY_X 32.0
#define BOUNDARY_Y 32.0
#define BOUNDARY_Z 32.0
#define CELL_LENGTH (2 * PARTICLE_RADIUS)
#define CELLS_IN_X ((int)(ceil(BOUNDARY_X / CELL_LENGTH)))
#define CELLS_IN_Y ((int)(ceil(BOUNDARY_Y / CELL_LENGTH)))
#define CELLS_IN_Z ((int)(ceil(BOUNDARY_Z / CELL_LENGTH)))
#define PARTICLES_PER_BLOCK 32
#define MAX_PARTICLES_PER_CELL 4
//#define SHARED_MEMORY_SIZE (1 << 14) // 16 KB
//#define MAX_CELLS_PER_BLOCK (SHARED_MEMORY_SIZE / (MAX_PARTICLES_PER_CELL * sizeof(Particle)))
//#define CELL_KERNEL_BLOCK_DEPTH (floor(cbrt(MAX_CELLS_PER_BLOCK)))
//#define CELL_KERNEL_BLOCK_WIDTH (floor(    (MAX_PARTICLES_PER_CELL - (CELL_KERNEL_BLOCK_DEPTH*CELL_KERNEL_BLOCK_DEPTH*CELL_KERNEL_BLOCK_DEPTH))   /   sqrt(MAX_PARTICLES_PER_CELL)    ))
//#define CELL_KERNEL_BLOCK_HEIGHT (floor(    MAX_PARTICLES_PER_CELL    /    (CELL_KERNEL_BLOCK_DEPTH * CELL_KERNEL_BLOCK_WIDTH)    ))
#define MAX_CELLS_PER_BLOCK 125
#define CELL_KERNEL_BLOCK_DEPTH 5
#define CELL_KERNEL_BLOCK_WIDTH 5
#define CELL_KERNEL_BLOCK_HEIGHT 5

#define NO_PARTICLE UINT_MAX
